### ISSUE TITLE
cannot identify image file 'all_compared_methods/MJRBM-VGG/EORSSD/1669.png'

### ISSUE THREAD

**Issue by nanfangAlan** [MathLee/CorrNet#1]
torch cannot identify the image file 'all_compared_methods/MJRBM-VGG/EORSSD/1669.png'
This image only has 20KB, so it seems to have some mistakes. Would you fix it? tks

**Comment by MathLee** [comment]
Attached is the picture you mentioned. Or you can download it from its official website https://github.com/wchao1213/ORSI-SOD.




在 2022-05-24 09:19:39，"nanfang" ***@***.***> 写道：

torch cannot identify the image file 'all_compared_methods/MJRBM-VGG/EORSSD/1669.png'
This image only has 20KB, so it seems to have some mistakes. Would you fix it? tks

**Comment by nanfangAlan** [comment]
Thank you very much!
